-- job_id: 91107621-3f77-440a-bdcb-59a46269e963
-- user: dataapps@variant.net
-- statement_type: SELECT
-- created: 2026-07-29T11:50:43.769000+00:00
-- started: 2026-07-29T11:50:43.863000+00:00
-- ended: 2026-07-29T11:50:44.274000+00:00


WITH m AS (SELECT Report_date d, Billing_Cycle bc, Product_Name_Final p, Spend_Country_Code_AFID cy, SUM(Recent_Users) ru
  FROM `variant-finance-data-project.Icarus_Spend_Country_AFID.SCA_7K_30D_Main_Table` WHERE Report_date > DATE_SUB(CURRENT_DATE(), INTERVAL 60 DAY) GROUP BY 1,2,3,4),
 f AS (SELECT Reporting_Date d, BC bc, Plan_Name p, Spend_Country_Code_AFID cy, SUM(`Subscriptions`) AS `Subscriptions`, SUM(`Rebills`) AS `Rebills`, SUM(`Single_Sale`) AS `Single_Sale`, SUM(`Churn_Rate`) AS `Churn_Rate`, SUM(`Refund_Rate`) AS `Refund_Rate`, SUM(`Cumulative_Refund_Rate`) AS `Cumulative_Refund_Rate`, SUM(`Gross_ARPU_Retention_Rate`) AS `Gross_ARPU_Retention_Rate`, SUM(`Net_ARPU_Retention_Rate`) AS `Net_ARPU_Retention_Rate`, SUM(`Recent_CAC`) AS `Recent_CAC`, SUM(`T30D_New_Users`) AS `T30D_New_Users`, SUM(`Daily_Spend`) AS `Daily_Spend`, SUM(`Daily_New_Users`) AS `Daily_New_Users`, SUM(`Daily_CAC`) AS `Daily_CAC`, SUM(`T7D_Daily_SS_Users`) AS `T7D_Daily_SS_Users`, SUM(`T7D_New_Users`) AS `T7D_New_Users`, SUM(`Gross_ARPU_Discounted`) AS `Gross_ARPU_Discounted`, SUM(`Net_ARPU_Discounted`) AS `Net_ARPU_Discounted`, SUM(`Net_LTV_Discounted`) AS `Net_LTV_Discounted`, SUM(`BC4_CAC_Ceiling`) AS `BC4_CAC_Ceiling`
  FROM `variant-finance-data-project.Icarus_Spend_Country_AFID.SCA_Final_Table` WHERE Cohort='7K_30D' AND `Table`='Regular'
    AND Reporting_Date > DATE_SUB(CURRENT_DATE(), INTERVAL 60 DAY) GROUP BY 1,2,3,4)
SELECT ROUND(CORR(m.ru, f.`Subscriptions`),4) AS `Subscriptions`, ROUND(CORR(m.ru, f.`Rebills`),4) AS `Rebills`, ROUND(CORR(m.ru, f.`Single_Sale`),4) AS `Single_Sale`, ROUND(CORR(m.ru, f.`Churn_Rate`),4) AS `Churn_Rate`, ROUND(CORR(m.ru, f.`Refund_Rate`),4) AS `Refund_Rate`, ROUND(CORR(m.ru, f.`Cumulative_Refund_Rate`),4) AS `Cumulative_Refund_Rate`, ROUND(CORR(m.ru, f.`Gross_ARPU_Retention_Rate`),4) AS `Gross_ARPU_Retention_Rate`, ROUND(CORR(m.ru, f.`Net_ARPU_Retention_Rate`),4) AS `Net_ARPU_Retention_Rate`, ROUND(CORR(m.ru, f.`Recent_CAC`),4) AS `Recent_CAC`, ROUND(CORR(m.ru, f.`T30D_New_Users`),4) AS `T30D_New_Users`, ROUND(CORR(m.ru, f.`Daily_Spend`),4) AS `Daily_Spend`, ROUND(CORR(m.ru, f.`Daily_New_Users`),4) AS `Daily_New_Users`, ROUND(CORR(m.ru, f.`Daily_CAC`),4) AS `Daily_CAC`, ROUND(CORR(m.ru, f.`T7D_Daily_SS_Users`),4) AS `T7D_Daily_SS_Users`, ROUND(CORR(m.ru, f.`T7D_New_Users`),4) AS `T7D_New_Users`, ROUND(CORR(m.ru, f.`Gross_ARPU_Discounted`),4) AS `Gross_ARPU_Discounted`, ROUND(CORR(m.ru, f.`Net_ARPU_Discounted`),4) AS `Net_ARPU_Discounted`, ROUND(CORR(m.ru, f.`Net_LTV_Discounted`),4) AS `Net_LTV_Discounted`, ROUND(CORR(m.ru, f.`BC4_CAC_Ceiling`),4) AS `BC4_CAC_Ceiling` FROM m JOIN f USING (d,bc,p,cy)
