-- job_id: 6b747cbc-d980-4bb3-a951-cad1f5c3cecb
-- user: dataapps@variant.net
-- statement_type: SELECT
-- created: 2026-07-29T11:22:18.499000+00:00
-- started: 2026-07-29T11:22:18.609000+00:00
-- ended: 2026-07-29T11:22:18.649000+00:00


WITH m AS (SELECT Report_date d, Billing_Cycle bc, Product_Name_Final p, Spend_Country_Code_AFID cy, SUM(T7D_Users) t7
           FROM `variant-finance-data-project.Icarus_Spend_Country_AFID.SCA_7K_30D_Main_Table`
           WHERE Report_date=(SELECT MAX(Report_date) FROM `variant-finance-data-project.Icarus_Spend_Country_AFID.SCA_7K_30D_Main_Table`) GROUP BY 1,2,3,4),
     f AS (SELECT Reporting_Date d, BC bc, Plan_Name p, Spend_Country_Code_AFID cy, SUM(`BC`) AS `BC`, SUM(`Subscriptions`) AS `Subscriptions`, SUM(`Rebills`) AS `Rebills`, SUM(`Single_Sale`) AS `Single_Sale`, SUM(`Churn_Rate`) AS `Churn_Rate`, SUM(`Refund_Rate`) AS `Refund_Rate`, SUM(`Cumulative_Refund_Rate`) AS `Cumulative_Refund_Rate`, SUM(`Gross_ARPU_Retention_Rate`) AS `Gross_ARPU_Retention_Rate`, SUM(`Net_ARPU_Retention_Rate`) AS `Net_ARPU_Retention_Rate`, SUM(`Recent_CAC`) AS `Recent_CAC`, SUM(`T30D_New_Users`) AS `T30D_New_Users`, SUM(`Daily_Spend`) AS `Daily_Spend`, SUM(`Daily_New_Users`) AS `Daily_New_Users`, SUM(`Daily_CAC`) AS `Daily_CAC`, SUM(`T7D_Daily_SS_Users`) AS `T7D_Daily_SS_Users`, SUM(`T7D_New_Users`) AS `T7D_New_Users`, SUM(`Gross_ARPU_Discounted`) AS `Gross_ARPU_Discounted`, SUM(`Net_ARPU_Discounted`) AS `Net_ARPU_Discounted`, SUM(`Net_LTV_Discounted`) AS `Net_LTV_Discounted`, SUM(`BC4_CAC_Ceiling`) AS `BC4_CAC_Ceiling`
           FROM `variant-finance-data-project.Icarus_Spend_Country_AFID.SCA_Final_Table` WHERE Cohort='7K_30D' AND `Table`='Regular'
             AND Reporting_Date=(SELECT MAX(Report_date) FROM `variant-finance-data-project.Icarus_Spend_Country_AFID.SCA_7K_30D_Main_Table`) GROUP BY 1,2,3,4)
SELECT ROUND(CORR(m.t7, f.`BC`),3) AS `BC`, ROUND(CORR(m.t7, f.`Subscriptions`),3) AS `Subscriptions`, ROUND(CORR(m.t7, f.`Rebills`),3) AS `Rebills`, ROUND(CORR(m.t7, f.`Single_Sale`),3) AS `Single_Sale`, ROUND(CORR(m.t7, f.`Churn_Rate`),3) AS `Churn_Rate`, ROUND(CORR(m.t7, f.`Refund_Rate`),3) AS `Refund_Rate`, ROUND(CORR(m.t7, f.`Cumulative_Refund_Rate`),3) AS `Cumulative_Refund_Rate`, ROUND(CORR(m.t7, f.`Gross_ARPU_Retention_Rate`),3) AS `Gross_ARPU_Retention_Rate`, ROUND(CORR(m.t7, f.`Net_ARPU_Retention_Rate`),3) AS `Net_ARPU_Retention_Rate`, ROUND(CORR(m.t7, f.`Recent_CAC`),3) AS `Recent_CAC`, ROUND(CORR(m.t7, f.`T30D_New_Users`),3) AS `T30D_New_Users`, ROUND(CORR(m.t7, f.`Daily_Spend`),3) AS `Daily_Spend`, ROUND(CORR(m.t7, f.`Daily_New_Users`),3) AS `Daily_New_Users`, ROUND(CORR(m.t7, f.`Daily_CAC`),3) AS `Daily_CAC`, ROUND(CORR(m.t7, f.`T7D_Daily_SS_Users`),3) AS `T7D_Daily_SS_Users`, ROUND(CORR(m.t7, f.`T7D_New_Users`),3) AS `T7D_New_Users`, ROUND(CORR(m.t7, f.`Gross_ARPU_Discounted`),3) AS `Gross_ARPU_Discounted`, ROUND(CORR(m.t7, f.`Net_ARPU_Discounted`),3) AS `Net_ARPU_Discounted`, ROUND(CORR(m.t7, f.`Net_LTV_Discounted`),3) AS `Net_LTV_Discounted`, ROUND(CORR(m.t7, f.`BC4_CAC_Ceiling`),3) AS `BC4_CAC_Ceiling` FROM m JOIN f USING (d,bc,p,cy)
