CREATE VIEW `variant-finance-data-project.chargebee.fct_orders_full`
AS WITH

i AS (
  SELECT
    id AS _i_id,
    JSON_VALUE(payload, '$.customer_id') AS _link_customer_id,
    JSON_VALUE(payload, '$.subscription_id') AS _link_subscription_id,
    JSON_VALUE(payload, '$.id') AS invoice_id,
    JSON_VALUE(payload, '$.customer_id') AS invoice_customer_id,
    JSON_VALUE(payload, '$.subscription_id') AS invoice_subscription_id,
    JSON_VALUE(payload, '$.recurring') AS recurring,
    JSON_VALUE(payload, '$.status') AS invoice_status,
    JSON_VALUE(payload, '$.date') AS invoice_date,
    JSON_VALUE(payload, '$.due_date') AS due_date,
    JSON_VALUE(payload, '$.net_term_days') AS invoice_net_term_days,
    JSON_VALUE(payload, '$.price_type') AS invoice_price_type,
    JSON_VALUE(payload, '$.exchange_rate') AS invoice_exchange_rate,
    JSON_VALUE(payload, '$.total') AS invoice_total,
    JSON_VALUE(payload, '$.amount_due') AS amount_due,
    JSON_VALUE(payload, '$.amount_adjusted') AS amount_adjusted,
    JSON_VALUE(payload, '$.amount_paid') AS amount_paid,
    JSON_VALUE(payload, '$.paid_at') AS paid_at,
    JSON_VALUE(payload, '$.write_off_amount') AS write_off_amount,
    JSON_VALUE(payload, '$.credits_applied') AS credits_applied,
    JSON_VALUE(payload, '$.updated_at') AS invoice_updated_at,
    JSON_VALUE(payload, '$.resource_version') AS invoice_resource_version,
    JSON_VALUE(payload, '$.deleted') AS invoice_deleted,
    JSON_VALUE(payload, '$.object') AS invoice_object,
    JSON_VALUE(payload, '$.first_invoice') AS first_invoice,
    JSON_VALUE(payload, '$.amount_to_collect') AS amount_to_collect,
    JSON_VALUE(payload, '$.round_off_amount') AS invoice_round_off_amount,
    JSON_VALUE(payload, '$.new_sales_amount') AS new_sales_amount,
    JSON_VALUE(payload, '$.has_advance_charges') AS has_advance_charges,
    JSON_VALUE(payload, '$.currency_code') AS invoice_currency_code,
    JSON_VALUE(payload, '$.base_currency_code') AS invoice_base_currency_code,
    JSON_VALUE(payload, '$.generated_at') AS invoice_generated_at,
    JSON_VALUE(payload, '$.is_gifted') AS is_gifted,
    JSON_VALUE(payload, '$.term_finalized') AS term_finalized,
    JSON_VALUE(payload, '$.channel') AS invoice_channel,
    JSON_VALUE(payload, '$.tax') AS tax,
    JSON_VALUE(payload, '$.sub_total') AS invoice_sub_total,
    JSON_VALUE(payload, '$.billing_address.city') AS billing_city,
    JSON_VALUE(payload, '$.billing_address.state_code') AS billing_state_code,
    JSON_VALUE(payload, '$.billing_address.state') AS billing_state,
    JSON_VALUE(payload, '$.billing_address.country') AS billing_country,
    JSON_VALUE(payload, '$.billing_address.zip') AS billing_zip,
    JSON_VALUE(payload, '$.billing_address.validation_status') AS billing_validation_status,
    JSON_VALUE(payload, '$.billing_address.object') AS billing_addr_object,
    JSON_VALUE(payload, '$.site_details_at_creation.timezone') AS site_timezone,
    JSON_VALUE(payload, '$.site_details_at_creation.organization_address.organization_name') AS site_org_name,
    JSON_VALUE(payload, '$.site_details_at_creation.organization_address.email') AS site_org_email,
    JSON_VALUE(payload, '$.site_details_at_creation.organization_address.line1') AS site_org_line1,
    JSON_VALUE(payload, '$.site_details_at_creation.organization_address.city') AS site_org_city,
    JSON_VALUE(payload, '$.site_details_at_creation.organization_address.state_code') AS site_org_state_code,
    JSON_VALUE(payload, '$.site_details_at_creation.organization_address.state') AS site_org_state,
    JSON_VALUE(payload, '$.site_details_at_creation.organization_address.country_code') AS site_org_country,
    JSON_VALUE(payload, '$.site_details_at_creation.organization_address.zip') AS site_org_zip,
    JSON_VALUE(payload, '$.site_details_at_creation.organization_address.phone') AS site_org_phone,
    JSON_VALUE(payload, '$.site_details_at_creation.organization_address.website') AS site_org_website,
    JSON_VALUE(payload, '$.site_details_at_creation.organization_address.currency_code') AS site_org_currency,
    JSON_VALUE(payload, '$.tax_origin.country') AS tax_origin_country,
    JSON_VALUE(payload, '$.billing_address.first_name') AS billing_first_name,
    JSON_VALUE(payload, '$.billing_address.last_name') AS billing_last_name,
    JSON_VALUE(payload, '$.dunning_status') AS dunning_status,
    ARRAY_LENGTH(JSON_QUERY_ARRAY(payload, '$.line_items')) AS line_items_count,
    JSON_VALUE(payload, '$.line_items[0].id') AS line1_id,
    JSON_VALUE(payload, '$.line_items[0].description') AS line1_description,
    JSON_VALUE(payload, '$.line_items[0].entity_id') AS line1_entity_id,
    JSON_VALUE(payload, '$.line_items[0].entity_type') AS line1_entity_type,
    JSON_VALUE(payload, '$.line_items[0].amount') AS line1_amount,
    JSON_VALUE(payload, '$.line_items[0].unit_amount') AS line1_unit_amount,
    JSON_VALUE(payload, '$.line_items[0].quantity') AS line1_quantity,
    JSON_VALUE(payload, '$.line_items[0].tax_amount') AS line1_tax_amount,
    JSON_VALUE(payload, '$.line_items[0].is_taxed') AS line1_is_taxed,
    JSON_VALUE(payload, '$.line_items[0].tax_exempt_reason') AS line1_tax_exempt_reason,
    JSON_VALUE(payload, '$.line_items[0].pricing_model') AS line1_pricing_model,
    JSON_VALUE(payload, '$.line_items[0].discount_amount') AS line1_discount_amount,
    JSON_VALUE(payload, '$.line_items[0].item_level_discount_amount') AS line1_item_level_discount_amount,
    JSON_VALUE(payload, '$.line_items[0].date_from') AS line1_date_from,
    JSON_VALUE(payload, '$.line_items[0].date_to') AS line1_date_to,
    JSON_VALUE(payload, '$.line_items[0].tax_rate') AS line1_tax_rate,
    JSON_VALUE(payload, '$.line_items[0].is_advance_charge') AS line1_is_advance_charge,
    JSON_VALUE(payload, '$.line_items[0].reference_line_item_id') AS line1_reference_line_item_id,
    JSON_VALUE(payload, '$.line_items[1].id') AS line2_id,
    JSON_VALUE(payload, '$.line_items[1].description') AS line2_description,
    JSON_VALUE(payload, '$.line_items[1].entity_id') AS line2_entity_id,
    JSON_VALUE(payload, '$.line_items[1].entity_type') AS line2_entity_type,
    JSON_VALUE(payload, '$.line_items[1].amount') AS line2_amount,
    JSON_VALUE(payload, '$.line_items[1].unit_amount') AS line2_unit_amount,
    JSON_VALUE(payload, '$.line_items[1].quantity') AS line2_quantity,
    JSON_VALUE(payload, '$.line_items[1].tax_amount') AS line2_tax_amount,
    JSON_VALUE(payload, '$.line_items[1].is_taxed') AS line2_is_taxed,
    JSON_VALUE(payload, '$.line_items[1].tax_exempt_reason') AS line2_tax_exempt_reason,
    JSON_VALUE(payload, '$.line_items[1].pricing_model') AS line2_pricing_model,
    JSON_VALUE(payload, '$.line_items[1].discount_amount') AS line2_discount_amount,
    JSON_VALUE(payload, '$.line_items[1].item_level_discount_amount') AS line2_item_level_discount_amount,
    JSON_VALUE(payload, '$.line_items[1].date_from') AS line2_date_from,
    JSON_VALUE(payload, '$.line_items[1].date_to') AS line2_date_to,
    JSON_VALUE(payload, '$.line_items[1].tax_rate') AS line2_tax_rate,
    JSON_VALUE(payload, '$.line_items[1].is_advance_charge') AS line2_is_advance_charge,
    JSON_VALUE(payload, '$.line_items[1].reference_line_item_id') AS line2_reference_line_item_id,
    JSON_VALUE(payload, '$.line_items[2].id') AS line3_id,
    JSON_VALUE(payload, '$.line_items[2].description') AS line3_description,
    JSON_VALUE(payload, '$.line_items[2].entity_id') AS line3_entity_id,
    JSON_VALUE(payload, '$.line_items[2].entity_type') AS line3_entity_type,
    JSON_VALUE(payload, '$.line_items[2].amount') AS line3_amount,
    JSON_VALUE(payload, '$.line_items[2].unit_amount') AS line3_unit_amount,
    JSON_VALUE(payload, '$.line_items[2].quantity') AS line3_quantity,
    JSON_VALUE(payload, '$.line_items[2].tax_amount') AS line3_tax_amount,
    JSON_VALUE(payload, '$.line_items[2].is_taxed') AS line3_is_taxed,
    JSON_VALUE(payload, '$.line_items[2].tax_exempt_reason') AS line3_tax_exempt_reason,
    JSON_VALUE(payload, '$.line_items[2].pricing_model') AS line3_pricing_model,
    JSON_VALUE(payload, '$.line_items[2].discount_amount') AS line3_discount_amount,
    JSON_VALUE(payload, '$.line_items[2].item_level_discount_amount') AS line3_item_level_discount_amount,
    JSON_VALUE(payload, '$.line_items[2].date_from') AS line3_date_from,
    JSON_VALUE(payload, '$.line_items[2].date_to') AS line3_date_to,
    JSON_VALUE(payload, '$.line_items[2].tax_rate') AS line3_tax_rate,
    JSON_VALUE(payload, '$.line_items[2].is_advance_charge') AS line3_is_advance_charge,
    JSON_VALUE(payload, '$.line_items[2].reference_line_item_id') AS line3_reference_line_item_id,
    ARRAY_LENGTH(JSON_QUERY_ARRAY(payload, '$.linked_payments')) AS linked_payments_count,
    JSON_VALUE(payload, '$.linked_payments[0].txn_id') AS payment_1_txn_id,
    JSON_VALUE(payload, '$.linked_payments[0].applied_amount') AS payment_1_applied_amount,
    JSON_VALUE(payload, '$.linked_payments[0].applied_at') AS payment_1_applied_at,
    JSON_VALUE(payload, '$.linked_payments[0].txn_status') AS payment_1_txn_status,
    JSON_VALUE(payload, '$.linked_payments[0].txn_date') AS payment_1_txn_date,
    JSON_VALUE(payload, '$.linked_payments[0].txn_amount') AS payment_1_txn_amount,
    JSON_VALUE(payload, '$.linked_payments[1].txn_id') AS payment_2_txn_id,
    JSON_VALUE(payload, '$.linked_payments[1].applied_amount') AS payment_2_applied_amount,
    JSON_VALUE(payload, '$.linked_payments[1].applied_at') AS payment_2_applied_at,
    JSON_VALUE(payload, '$.linked_payments[1].txn_status') AS payment_2_txn_status,
    JSON_VALUE(payload, '$.linked_payments[1].txn_date') AS payment_2_txn_date,
    JSON_VALUE(payload, '$.linked_payments[1].txn_amount') AS payment_2_txn_amount,
    ARRAY_LENGTH(JSON_QUERY_ARRAY(payload, '$.dunning_attempts')) AS dunning_attempts_count,
    JSON_VALUE(payload, '$.dunning_attempts[0].created_at') AS dunning_attempt_1_created_at,
    JSON_VALUE(payload, '$.dunning_attempts[0].attempt') AS dunning_attempt_1_attempt,
    JSON_VALUE(payload, '$.dunning_attempts[0].dunning_type') AS dunning_attempt_1_dunning_type,
    JSON_VALUE(payload, '$.dunning_attempts[0].retry_engine') AS dunning_attempt_1_retry_engine,
    JSON_VALUE(payload, '$.dunning_attempts[0].transaction_id') AS dunning_attempt_1_transaction_id,
    JSON_VALUE(payload, '$.dunning_attempts[0].txn_status') AS dunning_attempt_1_txn_status,
    JSON_VALUE(payload, '$.dunning_attempts[0].txn_amount') AS dunning_attempt_1_txn_amount,
    JSON_VALUE(payload, '$.dunning_attempts[1].created_at') AS dunning_attempt_2_created_at,
    JSON_VALUE(payload, '$.dunning_attempts[1].attempt') AS dunning_attempt_2_attempt,
    JSON_VALUE(payload, '$.dunning_attempts[1].dunning_type') AS dunning_attempt_2_dunning_type,
    JSON_VALUE(payload, '$.dunning_attempts[1].retry_engine') AS dunning_attempt_2_retry_engine,
    JSON_VALUE(payload, '$.dunning_attempts[1].transaction_id') AS dunning_attempt_2_transaction_id,
    JSON_VALUE(payload, '$.dunning_attempts[1].txn_status') AS dunning_attempt_2_txn_status,
    JSON_VALUE(payload, '$.dunning_attempts[1].txn_amount') AS dunning_attempt_2_txn_amount,
    JSON_VALUE(payload, '$.dunning_attempts[2].created_at') AS dunning_attempt_3_created_at,
    JSON_VALUE(payload, '$.dunning_attempts[2].attempt') AS dunning_attempt_3_attempt,
    JSON_VALUE(payload, '$.dunning_attempts[2].dunning_type') AS dunning_attempt_3_dunning_type,
    JSON_VALUE(payload, '$.dunning_attempts[2].retry_engine') AS dunning_attempt_3_retry_engine,
    JSON_VALUE(payload, '$.dunning_attempts[2].transaction_id') AS dunning_attempt_3_transaction_id,
    JSON_VALUE(payload, '$.dunning_attempts[2].txn_status') AS dunning_attempt_3_txn_status,
    JSON_VALUE(payload, '$.dunning_attempts[2].txn_amount') AS dunning_attempt_3_txn_amount,
    ARRAY_LENGTH(JSON_QUERY_ARRAY(payload, '$.issued_credit_notes')) AS issued_credit_notes_count,
    JSON_VALUE(payload, '$.issued_credit_notes[0].cn_id') AS refund_cn_1_cn_id,
    JSON_VALUE(payload, '$.issued_credit_notes[0].cn_reason_code') AS refund_cn_1_cn_reason_code,
    JSON_VALUE(payload, '$.issued_credit_notes[0].cn_create_reason_code') AS refund_cn_1_cn_create_reason_code,
    JSON_VALUE(payload, '$.issued_credit_notes[0].cn_date') AS refund_cn_1_cn_date,
    JSON_VALUE(payload, '$.issued_credit_notes[0].cn_total') AS refund_cn_1_cn_total,
    JSON_VALUE(payload, '$.issued_credit_notes[0].cn_status') AS refund_cn_1_cn_status,
    JSON_VALUE(payload, '$.issued_credit_notes[1].cn_id') AS refund_cn_2_cn_id,
    JSON_VALUE(payload, '$.issued_credit_notes[1].cn_reason_code') AS refund_cn_2_cn_reason_code,
    JSON_VALUE(payload, '$.issued_credit_notes[1].cn_create_reason_code') AS refund_cn_2_cn_create_reason_code,
    JSON_VALUE(payload, '$.issued_credit_notes[1].cn_date') AS refund_cn_2_cn_date,
    JSON_VALUE(payload, '$.issued_credit_notes[1].cn_total') AS refund_cn_2_cn_total,
    JSON_VALUE(payload, '$.issued_credit_notes[1].cn_status') AS refund_cn_2_cn_status,
    ARRAY_LENGTH(JSON_QUERY_ARRAY(payload, '$.reference_transactions')) AS reference_transactions_count,
    JSON_VALUE(payload, '$.reference_transactions[0].txn_id') AS ref_txn_1_txn_id,
    JSON_VALUE(payload, '$.reference_transactions[0].txn_type') AS ref_txn_1_txn_type,
    JSON_VALUE(payload, '$.reference_transactions[0].txn_status') AS ref_txn_1_txn_status,
    JSON_VALUE(payload, '$.reference_transactions[0].txn_date') AS ref_txn_1_txn_date,
    JSON_VALUE(payload, '$.reference_transactions[0].txn_amount') AS ref_txn_1_txn_amount,
    JSON_VALUE(payload, '$.reference_transactions[0].applied_amount') AS ref_txn_1_applied_amount,
    JSON_VALUE(payload, '$.reference_transactions[0].applied_at') AS ref_txn_1_applied_at,
    JSON_VALUE(payload, '$.reference_transactions[1].txn_id') AS ref_txn_2_txn_id,
    JSON_VALUE(payload, '$.reference_transactions[1].txn_type') AS ref_txn_2_txn_type,
    JSON_VALUE(payload, '$.reference_transactions[1].txn_status') AS ref_txn_2_txn_status,
    JSON_VALUE(payload, '$.reference_transactions[1].txn_date') AS ref_txn_2_txn_date,
    JSON_VALUE(payload, '$.reference_transactions[1].txn_amount') AS ref_txn_2_txn_amount,
    JSON_VALUE(payload, '$.reference_transactions[1].applied_amount') AS ref_txn_2_applied_amount,
    JSON_VALUE(payload, '$.reference_transactions[1].applied_at') AS ref_txn_2_applied_at,
    ARRAY_LENGTH(JSON_QUERY_ARRAY(payload, '$.applied_credits')) AS applied_credits_count,
    JSON_VALUE(payload, '$.applied_credits[0].cn_id') AS applied_credit_1_cn_id,
    JSON_VALUE(payload, '$.applied_credits[0].applied_amount') AS applied_credit_1_applied_amount,
    JSON_VALUE(payload, '$.applied_credits[0].applied_at') AS applied_credit_1_applied_at,
    JSON_VALUE(payload, '$.applied_credits[0].cn_reason_code') AS applied_credit_1_cn_reason_code,
    JSON_VALUE(payload, '$.applied_credits[0].cn_create_reason_code') AS applied_credit_1_cn_create_reason_code,
    JSON_VALUE(payload, '$.applied_credits[0].cn_date') AS applied_credit_1_cn_date,
    JSON_VALUE(payload, '$.applied_credits[0].cn_status') AS applied_credit_1_cn_status,
    JSON_VALUE(payload, '$.applied_credits[1].cn_id') AS applied_credit_2_cn_id,
    JSON_VALUE(payload, '$.applied_credits[1].applied_amount') AS applied_credit_2_applied_amount,
    JSON_VALUE(payload, '$.applied_credits[1].applied_at') AS applied_credit_2_applied_at,
    JSON_VALUE(payload, '$.applied_credits[1].cn_reason_code') AS applied_credit_2_cn_reason_code,
    JSON_VALUE(payload, '$.applied_credits[1].cn_create_reason_code') AS applied_credit_2_cn_create_reason_code,
    JSON_VALUE(payload, '$.applied_credits[1].cn_date') AS applied_credit_2_cn_date,
    JSON_VALUE(payload, '$.applied_credits[1].cn_status') AS applied_credit_2_cn_status,
    ARRAY_LENGTH(JSON_QUERY_ARRAY(payload, '$.adjustment_credit_notes')) AS adjustment_credit_notes_count,
    JSON_VALUE(payload, '$.adjustment_credit_notes[0].cn_id') AS adj_cn_1_cn_id,
    JSON_VALUE(payload, '$.adjustment_credit_notes[0].cn_reason_code') AS adj_cn_1_cn_reason_code,
    JSON_VALUE(payload, '$.adjustment_credit_notes[0].cn_create_reason_code') AS adj_cn_1_cn_create_reason_code,
    JSON_VALUE(payload, '$.adjustment_credit_notes[0].cn_date') AS adj_cn_1_cn_date,
    JSON_VALUE(payload, '$.adjustment_credit_notes[0].cn_total') AS adj_cn_1_cn_total,
    JSON_VALUE(payload, '$.adjustment_credit_notes[0].cn_status') AS adj_cn_1_cn_status,
    JSON_VALUE(payload, '$.adjustment_credit_notes[1].cn_id') AS adj_cn_2_cn_id,
    JSON_VALUE(payload, '$.adjustment_credit_notes[1].cn_reason_code') AS adj_cn_2_cn_reason_code,
    JSON_VALUE(payload, '$.adjustment_credit_notes[1].cn_create_reason_code') AS adj_cn_2_cn_create_reason_code,
    JSON_VALUE(payload, '$.adjustment_credit_notes[1].cn_date') AS adj_cn_2_cn_date,
    JSON_VALUE(payload, '$.adjustment_credit_notes[1].cn_total') AS adj_cn_2_cn_total,
    JSON_VALUE(payload, '$.adjustment_credit_notes[1].cn_status') AS adj_cn_2_cn_status,
    ARRAY_LENGTH(JSON_QUERY_ARRAY(payload, '$.linked_orders')) AS linked_orders_count,
    JSON_VALUE(payload, '$.linked_orders[0].id') AS order_1_id,
    JSON_VALUE(payload, '$.linked_orders[0].document_number') AS order_1_document_number,
    JSON_VALUE(payload, '$.linked_orders[0].status') AS order_1_status,
    JSON_VALUE(payload, '$.linked_orders[0].order_type') AS order_1_order_type,
    JSON_VALUE(payload, '$.linked_orders[0].reference_id') AS order_1_reference_id,
    JSON_VALUE(payload, '$.linked_orders[0].fulfillment_status') AS order_1_fulfillment_status,
    JSON_VALUE(payload, '$.linked_orders[0].batch_id') AS order_1_batch_id,
    JSON_VALUE(payload, '$.linked_orders[0].created_at') AS order_1_created_at,
    JSON_VALUE(payload, '$.linked_orders[1].id') AS order_2_id,
    JSON_VALUE(payload, '$.linked_orders[1].document_number') AS order_2_document_number,
    JSON_VALUE(payload, '$.linked_orders[1].status') AS order_2_status,
    JSON_VALUE(payload, '$.linked_orders[1].order_type') AS order_2_order_type,
    JSON_VALUE(payload, '$.linked_orders[1].reference_id') AS order_2_reference_id,
    JSON_VALUE(payload, '$.linked_orders[1].fulfillment_status') AS order_2_fulfillment_status,
    JSON_VALUE(payload, '$.linked_orders[1].batch_id') AS order_2_batch_id,
    JSON_VALUE(payload, '$.linked_orders[1].created_at') AS order_2_created_at,
    ARRAY_LENGTH(JSON_QUERY_ARRAY(payload, '$.discounts')) AS discounts_count,
    JSON_VALUE(payload, '$.discounts[0].amount') AS discount_1_amount,
    JSON_VALUE(payload, '$.discounts[0].description') AS discount_1_description,
    JSON_VALUE(payload, '$.discounts[0].entity_type') AS discount_1_entity_type,
    JSON_VALUE(payload, '$.discounts[0].entity_id') AS discount_1_entity_id,
    JSON_VALUE(payload, '$.discounts[0].coupon_set_code') AS discount_1_coupon_set_code,
    JSON_VALUE(payload, '$.discounts[0].discount_type') AS discount_1_discount_type,
    JSON_VALUE(payload, '$.discounts[1].amount') AS discount_2_amount,
    JSON_VALUE(payload, '$.discounts[1].description') AS discount_2_description,
    JSON_VALUE(payload, '$.discounts[1].entity_type') AS discount_2_entity_type,
    JSON_VALUE(payload, '$.discounts[1].entity_id') AS discount_2_entity_id,
    JSON_VALUE(payload, '$.discounts[1].coupon_set_code') AS discount_2_coupon_set_code,
    JSON_VALUE(payload, '$.discounts[1].discount_type') AS discount_2_discount_type,
    ARRAY_LENGTH(JSON_QUERY_ARRAY(payload, '$.taxes')) AS taxes_count,
    JSON_VALUE(payload, '$.taxes[0].name') AS tax_1_name,
    JSON_VALUE(payload, '$.taxes[0].amount') AS tax_1_amount,
    JSON_VALUE(payload, '$.taxes[0].description') AS tax_1_description,
    JSON_VALUE(payload, '$.taxes[1].name') AS tax_2_name,
    JSON_VALUE(payload, '$.taxes[1].amount') AS tax_2_amount,
    JSON_VALUE(payload, '$.taxes[1].description') AS tax_2_description,
    ARRAY_LENGTH(JSON_QUERY_ARRAY(payload, '$.line_item_taxes')) AS line_item_taxes_count,
    JSON_VALUE(payload, '$.line_item_taxes[0].line_item_id') AS line_tax_1_line_item_id,
    JSON_VALUE(payload, '$.line_item_taxes[0].tax_name') AS line_tax_1_tax_name,
    JSON_VALUE(payload, '$.line_item_taxes[0].tax_rate') AS line_tax_1_tax_rate,
    JSON_VALUE(payload, '$.line_item_taxes[0].is_partial_tax_applied') AS line_tax_1_is_partial_tax_applied,
    JSON_VALUE(payload, '$.line_item_taxes[0].is_non_compliance_tax') AS line_tax_1_is_non_compliance_tax,
    JSON_VALUE(payload, '$.line_item_taxes[0].taxable_amount') AS line_tax_1_taxable_amount,
    JSON_VALUE(payload, '$.line_item_taxes[0].tax_amount') AS line_tax_1_tax_amount,
    JSON_VALUE(payload, '$.line_item_taxes[0].tax_juris_type') AS line_tax_1_tax_juris_type,
    JSON_VALUE(payload, '$.line_item_taxes[0].tax_juris_name') AS line_tax_1_tax_juris_name,
    JSON_VALUE(payload, '$.line_item_taxes[0].tax_juris_code') AS line_tax_1_tax_juris_code,
    JSON_VALUE(payload, '$.line_item_taxes[1].line_item_id') AS line_tax_2_line_item_id,
    JSON_VALUE(payload, '$.line_item_taxes[1].tax_name') AS line_tax_2_tax_name,
    JSON_VALUE(payload, '$.line_item_taxes[1].tax_rate') AS line_tax_2_tax_rate,
    JSON_VALUE(payload, '$.line_item_taxes[1].is_partial_tax_applied') AS line_tax_2_is_partial_tax_applied,
    JSON_VALUE(payload, '$.line_item_taxes[1].is_non_compliance_tax') AS line_tax_2_is_non_compliance_tax,
    JSON_VALUE(payload, '$.line_item_taxes[1].taxable_amount') AS line_tax_2_taxable_amount,
    JSON_VALUE(payload, '$.line_item_taxes[1].tax_amount') AS line_tax_2_tax_amount,
    JSON_VALUE(payload, '$.line_item_taxes[1].tax_juris_type') AS line_tax_2_tax_juris_type,
    JSON_VALUE(payload, '$.line_item_taxes[1].tax_juris_name') AS line_tax_2_tax_juris_name,
    JSON_VALUE(payload, '$.line_item_taxes[1].tax_juris_code') AS line_tax_2_tax_juris_code,
    ARRAY_LENGTH(JSON_QUERY_ARRAY(payload, '$.line_item_discounts')) AS line_item_discounts_count,
    JSON_VALUE(payload, '$.line_item_discounts[0].line_item_id') AS line_discount_1_line_item_id,
    JSON_VALUE(payload, '$.line_item_discounts[0].discount_type') AS line_discount_1_discount_type,
    JSON_VALUE(payload, '$.line_item_discounts[0].coupon_id') AS line_discount_1_coupon_id,
    JSON_VALUE(payload, '$.line_item_discounts[0].entity_id') AS line_discount_1_entity_id,
    JSON_VALUE(payload, '$.line_item_discounts[0].discount_amount') AS line_discount_1_discount_amount,
    JSON_VALUE(payload, '$.line_item_discounts[1].line_item_id') AS line_discount_2_line_item_id,
    JSON_VALUE(payload, '$.line_item_discounts[1].discount_type') AS line_discount_2_discount_type,
    JSON_VALUE(payload, '$.line_item_discounts[1].coupon_id') AS line_discount_2_coupon_id,
    JSON_VALUE(payload, '$.line_item_discounts[1].entity_id') AS line_discount_2_entity_id,
    JSON_VALUE(payload, '$.line_item_discounts[1].discount_amount') AS line_discount_2_discount_amount
  FROM `variant-finance-data-project.chargebee_raw.invoices_raw`
),
c AS (
  SELECT
    id AS _c_id,
    JSON_VALUE(payload, '$.primary_payment_source_id') AS _link_payment_source_id,
    JSON_VALUE(payload, '$.id') AS customer_id,
    JSON_VALUE(payload, '$.email') AS customer_email,
    JSON_VALUE(payload, '$.auto_collection') AS customer_auto_collection,
    JSON_VALUE(payload, '$.net_term_days') AS customer_net_term_days,
    JSON_VALUE(payload, '$.allow_direct_debit') AS allow_direct_debit,
    JSON_VALUE(payload, '$.created_at') AS customer_created_at,
    JSON_VALUE(payload, '$.taxability') AS taxability,
    JSON_VALUE(payload, '$.updated_at') AS customer_updated_at,
    JSON_VALUE(payload, '$.pii_cleared') AS pii_cleared,
    JSON_VALUE(payload, '$.channel') AS customer_channel,
    JSON_VALUE(payload, '$.resource_version') AS customer_resource_version,
    JSON_VALUE(payload, '$.deleted') AS customer_deleted,
    JSON_VALUE(payload, '$.object') AS customer_object,
    JSON_VALUE(payload, '$.billing_address.city') AS cust_city,
    JSON_VALUE(payload, '$.billing_address.state_code') AS cust_state_code,
    JSON_VALUE(payload, '$.billing_address.state') AS cust_state,
    JSON_VALUE(payload, '$.billing_address.country') AS cust_country,
    JSON_VALUE(payload, '$.billing_address.zip') AS cust_zip,
    JSON_VALUE(payload, '$.billing_address.validation_status') AS cust_addr_validation_status,
    JSON_VALUE(payload, '$.billing_address.object') AS cust_addr_object,
    JSON_VALUE(payload, '$.card_status') AS card_status,
    JSON_VALUE(payload, '$.promotional_credits') AS promotional_credits,
    JSON_VALUE(payload, '$.refundable_credits') AS refundable_credits,
    JSON_VALUE(payload, '$.excess_payments') AS excess_payments,
    JSON_VALUE(payload, '$.unbilled_charges') AS unbilled_charges,
    JSON_VALUE(payload, '$.preferred_currency_code') AS preferred_currency_code,
    JSON_VALUE(payload, '$.mrr') AS customer_mrr,
    JSON_VALUE(payload, '$.primary_payment_source_id') AS primary_payment_source_id,
    JSON_VALUE(payload, '$.payment_method.object') AS payment_method_object,
    JSON_VALUE(payload, '$.payment_method.type') AS payment_method_type,
    JSON_VALUE(payload, '$.payment_method.reference_id') AS payment_method_reference_id,
    JSON_VALUE(payload, '$.payment_method.gateway') AS payment_method_gateway,
    JSON_VALUE(payload, '$.payment_method.gateway_account_id') AS payment_method_gateway_account_id,
    JSON_VALUE(payload, '$.payment_method.status') AS payment_method_status,
    JSON_VALUE(payload, '$.first_name') AS customer_first_name,
    JSON_VALUE(payload, '$.last_name') AS customer_last_name,
    JSON_VALUE(payload, '$.billing_address.first_name') AS cust_first_name,
    JSON_VALUE(payload, '$.billing_address.last_name') AS cust_last_name,
    JSON_VALUE(payload, '$.cf_afid') AS customer_cf_afid,
    JSON_VALUE(payload, '$.cf_sid') AS customer_cf_sid,
    JSON_VALUE(payload, '$.cf_c1') AS customer_cf_c1,
    JSON_VALUE(payload, '$.cf_c2') AS customer_cf_c2,
    JSON_VALUE(payload, '$.cf_c3') AS customer_cf_c3,
    JSON_VALUE(payload, '$.cf_click_id') AS customer_cf_click_id,
    JSON_VALUE(payload, '$.cf_campaign_id') AS customer_cf_campaign_id,
    JSON_VALUE(payload, '$.cf_source') AS customer_cf_source,
    JSON_VALUE(payload, '$.cf_sub_affiliate') AS customer_cf_sub_affiliate,
    JSON_VALUE(payload, '$.cf_affiliate') AS customer_cf_affiliate,
    JSON_VALUE(payload, '$.cf_aid') AS customer_cf_aid,
    JSON_VALUE(payload, '$.cf_opt') AS customer_cf_opt
  FROM `variant-finance-data-project.chargebee_raw.customers_raw`
),
s AS (
  SELECT
    id AS _s_id,
    JSON_VALUE(payload, '$.subscription_items[0].item_price_id') AS _link_item_price_id,
    JSON_VALUE(payload, '$.id') AS subscription_id,
    JSON_VALUE(payload, '$.billing_period') AS billing_period,
    JSON_VALUE(payload, '$.billing_period_unit') AS billing_period_unit,
    JSON_VALUE(payload, '$.trial_end') AS trial_end,
    JSON_VALUE(payload, '$.auto_collection') AS subscription_auto_collection,
    JSON_VALUE(payload, '$.customer_id') AS subscription_customer_id,
    JSON_VALUE(payload, '$.status') AS subscription_status,
    JSON_VALUE(payload, '$.trial_start') AS trial_start,
    JSON_VALUE(payload, '$.next_billing_at') AS next_billing_at,
    JSON_VALUE(payload, '$.created_at') AS subscription_created_at,
    JSON_VALUE(payload, '$.started_at') AS started_at,
    JSON_VALUE(payload, '$.updated_at') AS subscription_updated_at,
    JSON_VALUE(payload, '$.has_scheduled_changes') AS has_scheduled_changes,
    JSON_VALUE(payload, '$.channel') AS subscription_channel,
    JSON_VALUE(payload, '$.resource_version') AS subscription_resource_version,
    JSON_VALUE(payload, '$.deleted') AS subscription_deleted,
    JSON_VALUE(payload, '$.object') AS subscription_object,
    JSON_VALUE(payload, '$.currency_code') AS subscription_currency_code,
    JSON_VALUE(payload, '$.due_invoices_count') AS due_invoices_count,
    JSON_VALUE(payload, '$.has_scheduled_advance_invoices') AS has_scheduled_advance_invoices,
    JSON_VALUE(payload, '$.decommissioned') AS decommissioned,
    JSON_VALUE(payload, '$.meta_data.funnel') AS meta_data_funnel,
    JSON_VALUE(payload, '$.meta_data."plan-id"') AS meta_data_plan_id,
    JSON_VALUE(payload, '$.meta_data.category') AS meta_data_category,
    JSON_VALUE(payload, '$.remaining_billing_cycles') AS remaining_billing_cycles,
    JSON_VALUE(payload, '$.cancelled_at') AS cancelled_at,
    JSON_VALUE(payload, '$.cancel_schedule_created_at') AS cancel_schedule_created_at,
    JSON_VALUE(payload, '$.current_term_start') AS current_term_start,
    JSON_VALUE(payload, '$.current_term_end') AS current_term_end,
    JSON_VALUE(payload, '$.activated_at') AS activated_at,
    JSON_VALUE(payload, '$.mrr') AS subscription_mrr,
    JSON_VALUE(payload, '$.exchange_rate') AS subscription_exchange_rate,
    JSON_VALUE(payload, '$.base_currency_code') AS subscription_base_currency_code,
    JSON_VALUE(payload, '$.due_since') AS due_since,
    JSON_VALUE(payload, '$.total_dues') AS total_dues,
    JSON_VALUE(payload, '$.meta_data.afid') AS meta_data_afid,
    JSON_VALUE(payload, '$.meta_data.sid') AS meta_data_sid,
    JSON_VALUE(payload, '$.meta_data.c1') AS meta_data_c1,
    JSON_VALUE(payload, '$.meta_data.c2') AS meta_data_c2,
    JSON_VALUE(payload, '$.meta_data.c3') AS meta_data_c3,
    JSON_VALUE(payload, '$.meta_data.click_id') AS meta_data_click_id,
    JSON_VALUE(payload, '$.meta_data.campaign_id') AS meta_data_campaign_id,
    JSON_VALUE(payload, '$.meta_data.source') AS meta_data_source,
    JSON_VALUE(payload, '$.meta_data.sub_affiliate') AS meta_data_sub_affiliate,
    JSON_VALUE(payload, '$.meta_data.affiliate') AS meta_data_affiliate,
    JSON_VALUE(payload, '$.meta_data.aid') AS meta_data_aid,
    JSON_VALUE(payload, '$.meta_data.opt') AS meta_data_opt,
    JSON_VALUE(payload, '$.cf_afid') AS cf_afid,
    JSON_VALUE(payload, '$.cf_sid') AS cf_sid,
    JSON_VALUE(payload, '$.cf_c1') AS cf_c1,
    JSON_VALUE(payload, '$.cf_c2') AS cf_c2,
    JSON_VALUE(payload, '$.cf_c3') AS cf_c3,
    JSON_VALUE(payload, '$.cf_click_id') AS cf_click_id,
    JSON_VALUE(payload, '$.cf_campaign_id') AS cf_campaign_id,
    JSON_VALUE(payload, '$.cf_source') AS cf_source,
    JSON_VALUE(payload, '$.cf_sub_affiliate') AS cf_sub_affiliate,
    JSON_VALUE(payload, '$.cf_affiliate') AS cf_affiliate,
    JSON_VALUE(payload, '$.cf_aid') AS cf_aid,
    JSON_VALUE(payload, '$.cf_opt') AS cf_opt,
    COALESCE(JSON_VALUE(payload, '$.cf_afid'), JSON_VALUE(payload, '$.meta_data.afid')) AS afid,
    COALESCE(JSON_VALUE(payload, '$.cf_sid'), JSON_VALUE(payload, '$.meta_data.sid')) AS sid,
    COALESCE(JSON_VALUE(payload, '$.cf_c1'), JSON_VALUE(payload, '$.meta_data.c1')) AS c1,
    COALESCE(JSON_VALUE(payload, '$.cf_c2'), JSON_VALUE(payload, '$.meta_data.c2')) AS c2,
    COALESCE(JSON_VALUE(payload, '$.cf_c3'), JSON_VALUE(payload, '$.meta_data.c3')) AS c3,
    COALESCE(JSON_VALUE(payload, '$.cf_click_id'), JSON_VALUE(payload, '$.meta_data.click_id')) AS click_id,
    COALESCE(JSON_VALUE(payload, '$.cf_campaign_id'), JSON_VALUE(payload, '$.meta_data.campaign_id')) AS campaign_id,
    COALESCE(JSON_VALUE(payload, '$.cf_source'), JSON_VALUE(payload, '$.meta_data.source')) AS source,
    COALESCE(JSON_VALUE(payload, '$.cf_sub_affiliate'), JSON_VALUE(payload, '$.meta_data.sub_affiliate')) AS sub_affiliate,
    COALESCE(JSON_VALUE(payload, '$.cf_affiliate'), JSON_VALUE(payload, '$.meta_data.affiliate')) AS affiliate,
    COALESCE(JSON_VALUE(payload, '$.cf_aid'), JSON_VALUE(payload, '$.meta_data.aid')) AS aid,
    COALESCE(JSON_VALUE(payload, '$.cf_opt'), JSON_VALUE(payload, '$.meta_data.opt')) AS opt,
    ARRAY_LENGTH(JSON_QUERY_ARRAY(payload, '$.subscription_items')) AS subscription_items_count,
    JSON_VALUE(payload, '$.subscription_items[0].item_price_id') AS plan_item_price_id,
    JSON_VALUE(payload, '$.subscription_items[0].item_type') AS plan_item_type,
    JSON_VALUE(payload, '$.subscription_items[0].quantity') AS plan_quantity,
    JSON_VALUE(payload, '$.subscription_items[0].unit_price') AS plan_unit_price,
    JSON_VALUE(payload, '$.subscription_items[0].amount') AS plan_amount,
    JSON_VALUE(payload, '$.subscription_items[0].free_quantity') AS plan_free_quantity,
    JSON_VALUE(payload, '$.subscription_items[0].trial_end') AS plan_trial_end,
    JSON_VALUE(payload, '$.subscription_items[0].charge_on_event') AS plan_charge_on_event,
    JSON_VALUE(payload, '$.subscription_items[0].charge_once') AS plan_charge_once,
    JSON_VALUE(payload, '$.subscription_items[0].billing_cycles') AS plan_billing_cycles,
    JSON_VALUE(payload, '$.subscription_items[0].service_period_days') AS plan_service_period_days,
    JSON_VALUE(payload, '$.subscription_items[0].charge_on_option') AS plan_charge_on_option,
    JSON_VALUE(payload, '$.subscription_items[1].item_price_id') AS trial_charge_item_price_id,
    JSON_VALUE(payload, '$.subscription_items[1].item_type') AS trial_charge_item_type,
    JSON_VALUE(payload, '$.subscription_items[1].quantity') AS trial_charge_quantity,
    JSON_VALUE(payload, '$.subscription_items[1].unit_price') AS trial_charge_unit_price,
    JSON_VALUE(payload, '$.subscription_items[1].amount') AS trial_charge_amount,
    JSON_VALUE(payload, '$.subscription_items[1].free_quantity') AS trial_charge_free_quantity,
    JSON_VALUE(payload, '$.subscription_items[1].trial_end') AS trial_charge_trial_end,
    JSON_VALUE(payload, '$.subscription_items[1].charge_on_event') AS trial_charge_charge_on_event,
    JSON_VALUE(payload, '$.subscription_items[1].charge_once') AS trial_charge_charge_once,
    JSON_VALUE(payload, '$.subscription_items[1].billing_cycles') AS trial_charge_billing_cycles,
    JSON_VALUE(payload, '$.subscription_items[1].service_period_days') AS trial_charge_service_period_days,
    JSON_VALUE(payload, '$.subscription_items[1].charge_on_option') AS trial_charge_charge_on_option,
    JSON_VALUE(payload, '$.subscription_items[2].item_price_id') AS addon_1_item_price_id,
    JSON_VALUE(payload, '$.subscription_items[2].item_type') AS addon_1_item_type,
    JSON_VALUE(payload, '$.subscription_items[2].quantity') AS addon_1_quantity,
    JSON_VALUE(payload, '$.subscription_items[2].unit_price') AS addon_1_unit_price,
    JSON_VALUE(payload, '$.subscription_items[2].amount') AS addon_1_amount,
    JSON_VALUE(payload, '$.subscription_items[2].free_quantity') AS addon_1_free_quantity,
    JSON_VALUE(payload, '$.subscription_items[2].trial_end') AS addon_1_trial_end,
    JSON_VALUE(payload, '$.subscription_items[2].charge_on_event') AS addon_1_charge_on_event,
    JSON_VALUE(payload, '$.subscription_items[2].charge_once') AS addon_1_charge_once,
    JSON_VALUE(payload, '$.subscription_items[2].billing_cycles') AS addon_1_billing_cycles,
    JSON_VALUE(payload, '$.subscription_items[2].service_period_days') AS addon_1_service_period_days,
    JSON_VALUE(payload, '$.subscription_items[2].charge_on_option') AS addon_1_charge_on_option,
    JSON_VALUE(payload, '$.subscription_items[3].item_price_id') AS addon_2_item_price_id,
    JSON_VALUE(payload, '$.subscription_items[3].item_type') AS addon_2_item_type,
    JSON_VALUE(payload, '$.subscription_items[3].quantity') AS addon_2_quantity,
    JSON_VALUE(payload, '$.subscription_items[3].unit_price') AS addon_2_unit_price,
    JSON_VALUE(payload, '$.subscription_items[3].amount') AS addon_2_amount,
    JSON_VALUE(payload, '$.subscription_items[3].free_quantity') AS addon_2_free_quantity,
    JSON_VALUE(payload, '$.subscription_items[3].trial_end') AS addon_2_trial_end,
    JSON_VALUE(payload, '$.subscription_items[3].charge_on_event') AS addon_2_charge_on_event,
    JSON_VALUE(payload, '$.subscription_items[3].charge_once') AS addon_2_charge_once,
    JSON_VALUE(payload, '$.subscription_items[3].billing_cycles') AS addon_2_billing_cycles,
    JSON_VALUE(payload, '$.subscription_items[3].service_period_days') AS addon_2_service_period_days,
    JSON_VALUE(payload, '$.subscription_items[3].charge_on_option') AS addon_2_charge_on_option,
    ARRAY_LENGTH(JSON_QUERY_ARRAY(payload, '$.charged_items')) AS charged_items_count,
    JSON_VALUE(payload, '$.charged_items[0].item_price_id') AS charged_1_item_price_id,
    JSON_VALUE(payload, '$.charged_items[0].last_charged_at') AS charged_1_last_charged_at,
    JSON_VALUE(payload, '$.charged_items[1].item_price_id') AS charged_2_item_price_id,
    JSON_VALUE(payload, '$.charged_items[1].last_charged_at') AS charged_2_last_charged_at
  FROM `variant-finance-data-project.chargebee_raw.subscriptions_raw`
),
t AS (
  SELECT * EXCEPT(rn) FROM (
    SELECT
      JSON_VALUE(li, '$.invoice_id') AS _link_invoice_id,

      JSON_VALUE(t.payload, '$.id') AS transaction_id,
      JSON_VALUE(t.payload, '$.customer_id') AS transaction_customer_id,
      JSON_VALUE(t.payload, '$.subscription_id') AS transaction_subscription_id,
      JSON_VALUE(t.payload, '$.gateway_account_id') AS transaction_gateway_account_id,
      JSON_VALUE(t.payload, '$.payment_source_id') AS payment_source_id,
      JSON_VALUE(t.payload, '$.payment_method') AS payment_method,
      JSON_VALUE(t.payload, '$.gateway') AS transaction_gateway,
      JSON_VALUE(t.payload, '$.type') AS transaction_type,
      JSON_VALUE(t.payload, '$.date') AS transaction_date,
      JSON_VALUE(t.payload, '$.settled_at') AS settled_at,
      JSON_VALUE(t.payload, '$.exchange_rate') AS transaction_exchange_rate,
      JSON_VALUE(t.payload, '$.amount') AS amount,
      JSON_VALUE(t.payload, '$.id_at_gateway') AS id_at_gateway,
      JSON_VALUE(t.payload, '$.status') AS transaction_status,
      JSON_VALUE(t.payload, '$.updated_at') AS transaction_updated_at,
      JSON_VALUE(t.payload, '$.resource_version') AS transaction_resource_version,
      JSON_VALUE(t.payload, '$.deleted') AS transaction_deleted,
      JSON_VALUE(t.payload, '$.object') AS transaction_object,
      JSON_VALUE(t.payload, '$.masked_card_number') AS masked_card_number,
      JSON_VALUE(t.payload, '$.currency_code') AS transaction_currency_code,
      JSON_VALUE(t.payload, '$.base_currency_code') AS transaction_base_currency_code,
      JSON_VALUE(t.payload, '$.amount_unused') AS amount_unused,
      JSON_VALUE(t.payload, '$.initiator_type') AS initiator_type,
      JSON_VALUE(t.payload, '$.three_d_secure') AS three_d_secure,
      JSON_VALUE(t.payload, '$.error_code') AS error_code,
      JSON_VALUE(t.payload, '$.error_text') AS error_text,
      JSON_VALUE(t.payload, '$.error_detail.network_error_code') AS error_detail_network_error_code,
      JSON_VALUE(t.payload, '$.error_detail.network_error_message') AS error_detail_network_error_message,
      JSON_VALUE(t.payload, '$.error_detail.processor_error_code') AS error_detail_processor_error_code,
      JSON_VALUE(t.payload, '$.error_detail.processor_error_message') AS error_detail_processor_error_message,
      JSON_VALUE(t.payload, '$.error_detail.error_cause_id') AS error_detail_error_cause_id,
      JSON_VALUE(t.payload, '$.error_detail.processor_advice_code') AS error_detail_processor_advice_code,
      JSON_VALUE(t.payload, '$.error_detail.object') AS error_detail_object,
      JSON_VALUE(t.payload, '$.error_detail.request_id') AS error_detail_request_id,
      JSON_VALUE(t.payload, '$.error_detail.error_code') AS error_detail_error_code,
      JSON_VALUE(t.payload, '$.error_detail.error_message') AS error_detail_error_message,
      JSON_VALUE(t.payload, '$.error_detail.recommendation_code') AS error_detail_recommendation_code,
      JSON_VALUE(t.payload, '$.refunded_txn_id') AS refunded_txn_id,
      JSON_VALUE(PARSE_JSON(JSON_VALUE(t.payload, '$.payment_method_details')), '$.card.iin') AS txn_card_iin,
      JSON_VALUE(PARSE_JSON(JSON_VALUE(t.payload, '$.payment_method_details')), '$.card.last4') AS txn_card_last4,
      JSON_VALUE(PARSE_JSON(JSON_VALUE(t.payload, '$.payment_method_details')), '$.card.funding_type') AS txn_card_funding_type,
      JSON_VALUE(PARSE_JSON(JSON_VALUE(t.payload, '$.payment_method_details')), '$.card.expiry_month') AS txn_card_expiry_month,
      JSON_VALUE(PARSE_JSON(JSON_VALUE(t.payload, '$.payment_method_details')), '$.card.expiry_year') AS txn_card_expiry_year,
      JSON_VALUE(PARSE_JSON(JSON_VALUE(t.payload, '$.payment_method_details')), '$.card.billing_city') AS txn_card_billing_city,
      JSON_VALUE(PARSE_JSON(JSON_VALUE(t.payload, '$.payment_method_details')), '$.card.billing_state') AS txn_card_billing_state,
      JSON_VALUE(PARSE_JSON(JSON_VALUE(t.payload, '$.payment_method_details')), '$.card.billing_country') AS txn_card_billing_country,
      JSON_VALUE(PARSE_JSON(JSON_VALUE(t.payload, '$.payment_method_details')), '$.card.billing_zip') AS txn_card_billing_zip,
      JSON_VALUE(PARSE_JSON(JSON_VALUE(t.payload, '$.payment_method_details')), '$.card.masked_number') AS txn_card_masked_number,
      JSON_VALUE(PARSE_JSON(JSON_VALUE(t.payload, '$.payment_method_details')), '$.card.brand') AS txn_card_brand,
      ARRAY_LENGTH(JSON_QUERY_ARRAY(t.payload, '$.linked_invoices')) AS linked_invoices_count,
      JSON_VALUE(t.payload, '$.linked_invoices[0].invoice_id') AS txn_inv_1_invoice_id,
      JSON_VALUE(t.payload, '$.linked_invoices[0].applied_amount') AS txn_inv_1_applied_amount,
      JSON_VALUE(t.payload, '$.linked_invoices[0].applied_at') AS txn_inv_1_applied_at,
      JSON_VALUE(t.payload, '$.linked_invoices[0].invoice_date') AS txn_inv_1_invoice_date,
      JSON_VALUE(t.payload, '$.linked_invoices[0].invoice_total') AS txn_inv_1_invoice_total,
      JSON_VALUE(t.payload, '$.linked_invoices[0].invoice_status') AS txn_inv_1_invoice_status,
      JSON_VALUE(t.payload, '$.linked_invoices[1].invoice_id') AS txn_inv_2_invoice_id,
      JSON_VALUE(t.payload, '$.linked_invoices[1].applied_amount') AS txn_inv_2_applied_amount,
      JSON_VALUE(t.payload, '$.linked_invoices[1].applied_at') AS txn_inv_2_applied_at,
      JSON_VALUE(t.payload, '$.linked_invoices[1].invoice_date') AS txn_inv_2_invoice_date,
      JSON_VALUE(t.payload, '$.linked_invoices[1].invoice_total') AS txn_inv_2_invoice_total,
      JSON_VALUE(t.payload, '$.linked_invoices[1].invoice_status') AS txn_inv_2_invoice_status,
      ARRAY_LENGTH(JSON_QUERY_ARRAY(t.payload, '$.linked_credit_notes')) AS linked_credit_notes_count,
      JSON_VALUE(t.payload, '$.linked_credit_notes[0].cn_id') AS txn_cn_1_cn_id,
      JSON_VALUE(t.payload, '$.linked_credit_notes[0].cn_reason_code') AS txn_cn_1_cn_reason_code,
      JSON_VALUE(t.payload, '$.linked_credit_notes[0].cn_create_reason_code') AS txn_cn_1_cn_create_reason_code,
      JSON_VALUE(t.payload, '$.linked_credit_notes[0].cn_date') AS txn_cn_1_cn_date,
      JSON_VALUE(t.payload, '$.linked_credit_notes[0].cn_total') AS txn_cn_1_cn_total,
      JSON_VALUE(t.payload, '$.linked_credit_notes[0].cn_status') AS txn_cn_1_cn_status,
      JSON_VALUE(t.payload, '$.linked_credit_notes[0].applied_amount') AS txn_cn_1_applied_amount,
      JSON_VALUE(t.payload, '$.linked_credit_notes[0].applied_at') AS txn_cn_1_applied_at,
      JSON_VALUE(t.payload, '$.linked_credit_notes[0].cn_reference_invoice_id') AS txn_cn_1_cn_reference_invoice_id,
      JSON_VALUE(t.payload, '$.linked_credit_notes[1].cn_id') AS txn_cn_2_cn_id,
      JSON_VALUE(t.payload, '$.linked_credit_notes[1].cn_reason_code') AS txn_cn_2_cn_reason_code,
      JSON_VALUE(t.payload, '$.linked_credit_notes[1].cn_create_reason_code') AS txn_cn_2_cn_create_reason_code,
      JSON_VALUE(t.payload, '$.linked_credit_notes[1].cn_date') AS txn_cn_2_cn_date,
      JSON_VALUE(t.payload, '$.linked_credit_notes[1].cn_total') AS txn_cn_2_cn_total,
      JSON_VALUE(t.payload, '$.linked_credit_notes[1].cn_status') AS txn_cn_2_cn_status,
      JSON_VALUE(t.payload, '$.linked_credit_notes[1].applied_amount') AS txn_cn_2_applied_amount,
      JSON_VALUE(t.payload, '$.linked_credit_notes[1].applied_at') AS txn_cn_2_applied_at,
      JSON_VALUE(t.payload, '$.linked_credit_notes[1].cn_reference_invoice_id') AS txn_cn_2_cn_reference_invoice_id,
      ARRAY_LENGTH(JSON_QUERY_ARRAY(t.payload, '$.linked_refunds')) AS linked_refunds_count,
      JSON_VALUE(t.payload, '$.linked_refunds[0].txn_id') AS txn_refund_1_txn_id,
      JSON_VALUE(t.payload, '$.linked_refunds[0].txn_status') AS txn_refund_1_txn_status,
      JSON_VALUE(t.payload, '$.linked_refunds[0].txn_date') AS txn_refund_1_txn_date,
      JSON_VALUE(t.payload, '$.linked_refunds[0].txn_amount') AS txn_refund_1_txn_amount,
      JSON_VALUE(t.payload, '$.linked_refunds[1].txn_id') AS txn_refund_2_txn_id,
      JSON_VALUE(t.payload, '$.linked_refunds[1].txn_status') AS txn_refund_2_txn_status,
      JSON_VALUE(t.payload, '$.linked_refunds[1].txn_date') AS txn_refund_2_txn_date,
      JSON_VALUE(t.payload, '$.linked_refunds[1].txn_amount') AS txn_refund_2_txn_amount,
      ROW_NUMBER() OVER (PARTITION BY JSON_VALUE(li, '$.invoice_id')
        ORDER BY SAFE_CAST(JSON_VALUE(t.payload, '$.date') AS INT64) DESC) AS rn
    FROM `variant-finance-data-project.chargebee_raw.transactions_raw` t,
         UNNEST(JSON_QUERY_ARRAY(payload, '$.linked_invoices')) AS li
  ) WHERE rn = 1
),
cn AS (
  SELECT * EXCEPT(rn) FROM (
    SELECT
      JSON_VALUE(c.payload, '$.reference_invoice_id') AS _link_invoice_id,
      COUNT(*) OVER (PARTITION BY JSON_VALUE(c.payload, '$.reference_invoice_id')) AS cn_count,
      SUM(SAFE_CAST(JSON_VALUE(c.payload, '$.amount_refunded') AS INT64))
        OVER (PARTITION BY JSON_VALUE(c.payload, '$.reference_invoice_id')) AS cn_total_amount_refunded,
      SUM(SAFE_CAST(JSON_VALUE(c.payload, '$.total') AS INT64))
        OVER (PARTITION BY JSON_VALUE(c.payload, '$.reference_invoice_id')) AS cn_total_credit_amount,

      JSON_VALUE(c.payload, '$.id') AS cn_id,
      JSON_VALUE(c.payload, '$.type') AS cn_type,
      JSON_VALUE(c.payload, '$.reason_code') AS cn_reason_code,
      JSON_VALUE(c.payload, '$.status') AS cn_status,
      JSON_VALUE(c.payload, '$.date') AS cn_date,
      JSON_VALUE(c.payload, '$.price_type') AS cn_price_type,
      JSON_VALUE(c.payload, '$.exchange_rate') AS cn_exchange_rate,
      JSON_VALUE(c.payload, '$.total') AS cn_total,
      JSON_VALUE(c.payload, '$.amount_allocated') AS cn_amount_allocated,
      JSON_VALUE(c.payload, '$.amount_refunded') AS cn_amount_refunded,
      JSON_VALUE(c.payload, '$.amount_available') AS cn_amount_available,
      JSON_VALUE(c.payload, '$.refunded_at') AS cn_refunded_at,
      JSON_VALUE(c.payload, '$.generated_at') AS cn_generated_at,
      JSON_VALUE(c.payload, '$.updated_at') AS cn_updated_at,
      JSON_VALUE(c.payload, '$.channel') AS cn_channel,
      JSON_VALUE(c.payload, '$.resource_version') AS cn_resource_version,
      JSON_VALUE(c.payload, '$.deleted') AS cn_deleted,
      JSON_VALUE(c.payload, '$.object') AS cn_object,
      JSON_VALUE(c.payload, '$.create_reason_code') AS cn_create_reason_code,
      JSON_VALUE(c.payload, '$.currency_code') AS cn_currency_code,
      JSON_VALUE(c.payload, '$.round_off_amount') AS cn_round_off_amount,
      JSON_VALUE(c.payload, '$.fractional_correction') AS cn_fractional_correction,
      JSON_VALUE(c.payload, '$.base_currency_code') AS cn_base_currency_code,
      JSON_VALUE(c.payload, '$.sub_total') AS cn_sub_total,
      JSON_VALUE(c.payload, '$.customer_notes') AS cn_customer_notes,
      ARRAY_LENGTH(JSON_QUERY_ARRAY(c.payload, '$.linked_refunds')) AS cn_linked_refunds_count,
      JSON_VALUE(c.payload, '$.linked_refunds[0].txn_id') AS cn_refund_1_txn_id,
      JSON_VALUE(c.payload, '$.linked_refunds[0].txn_status') AS cn_refund_1_txn_status,
      JSON_VALUE(c.payload, '$.linked_refunds[0].txn_date') AS cn_refund_1_txn_date,
      JSON_VALUE(c.payload, '$.linked_refunds[0].txn_amount') AS cn_refund_1_txn_amount,
      JSON_VALUE(c.payload, '$.linked_refunds[0].applied_amount') AS cn_refund_1_applied_amount,
      JSON_VALUE(c.payload, '$.linked_refunds[0].applied_at') AS cn_refund_1_applied_at,
      JSON_VALUE(c.payload, '$.linked_refunds[1].txn_id') AS cn_refund_2_txn_id,
      JSON_VALUE(c.payload, '$.linked_refunds[1].txn_status') AS cn_refund_2_txn_status,
      JSON_VALUE(c.payload, '$.linked_refunds[1].txn_date') AS cn_refund_2_txn_date,
      JSON_VALUE(c.payload, '$.linked_refunds[1].txn_amount') AS cn_refund_2_txn_amount,
      JSON_VALUE(c.payload, '$.linked_refunds[1].applied_amount') AS cn_refund_2_applied_amount,
      JSON_VALUE(c.payload, '$.linked_refunds[1].applied_at') AS cn_refund_2_applied_at,
      JSON_VALUE(c.payload, '$.notes[0]') AS cn_notes_1,
      ROW_NUMBER() OVER (PARTITION BY JSON_VALUE(c.payload, '$.reference_invoice_id')
        ORDER BY SAFE_CAST(JSON_VALUE(c.payload, '$.date') AS INT64) DESC) AS rn
    FROM `variant-finance-data-project.chargebee_raw.credit_notes_raw` c
  ) WHERE rn = 1
),
ps AS (
  SELECT
    id AS _ps_id,
    JSON_VALUE(payload, '$.id') AS card_id,
    JSON_VALUE(payload, '$.updated_at') AS card_updated_at,
    JSON_VALUE(payload, '$.resource_version') AS card_resource_version,
    JSON_VALUE(payload, '$.deleted') AS card_deleted,
    JSON_VALUE(payload, '$.object') AS card_object,
    JSON_VALUE(payload, '$.customer_id') AS card_customer_id,
    JSON_VALUE(payload, '$.type') AS card_type,
    JSON_VALUE(payload, '$.reference_id') AS reference_id,
    JSON_VALUE(payload, '$.status') AS card_status,
    JSON_VALUE(payload, '$.gateway') AS card_gateway,
    JSON_VALUE(payload, '$.gateway_account_id') AS card_gateway_account_id,
    JSON_VALUE(payload, '$.issuing_country') AS issuing_country,
    JSON_VALUE(payload, '$.ip_address') AS ip_address,
    JSON_VALUE(payload, '$.created_at') AS card_created_at,
    JSON_VALUE(payload, '$.card.iin') AS card_iin,
    JSON_VALUE(payload, '$.card.last4') AS card_last4,
    JSON_VALUE(payload, '$.card.funding_type') AS card_funding_type,
    JSON_VALUE(payload, '$.card.expiry_month') AS card_expiry_month,
    JSON_VALUE(payload, '$.card.expiry_year') AS card_expiry_year,
    JSON_VALUE(payload, '$.card.billing_city') AS card_billing_city,
    JSON_VALUE(payload, '$.card.billing_state_code') AS card_billing_state_code,
    JSON_VALUE(payload, '$.card.billing_state') AS card_billing_state,
    JSON_VALUE(payload, '$.card.billing_country') AS card_billing_country,
    JSON_VALUE(payload, '$.card.billing_zip') AS card_billing_zip,
    JSON_VALUE(payload, '$.card.masked_number') AS card_masked_number,
    JSON_VALUE(payload, '$.card.object') AS card_object_2,
    JSON_VALUE(payload, '$.card.brand') AS card_brand,
    JSON_VALUE(payload, '$.paypal.email') AS paypal_email,
    JSON_VALUE(payload, '$.paypal.agreement_id') AS paypal_agreement_id,
    JSON_VALUE(payload, '$.paypal.object') AS paypal_object
  FROM `variant-finance-data-project.chargebee_raw.payment_sources_raw`
),
ip AS (
  SELECT
    id AS _ip_id,
    JSON_VALUE(payload, '$.item_id') AS _link_item_id,
    JSON_VALUE(payload, '$.id') AS offer_id,
    JSON_VALUE(payload, '$.name') AS offer_name,
    JSON_VALUE(payload, '$.item_family_id') AS offer_item_family_id,
    JSON_VALUE(payload, '$.item_id') AS item_id,
    JSON_VALUE(payload, '$.status') AS offer_status,
    JSON_VALUE(payload, '$.external_name') AS offer_external_name,
    JSON_VALUE(payload, '$.pricing_model') AS pricing_model,
    JSON_VALUE(payload, '$.price') AS price,
    JSON_VALUE(payload, '$.period') AS period,
    JSON_VALUE(payload, '$.currency_code') AS offer_currency_code,
    JSON_VALUE(payload, '$.period_unit') AS period_unit,
    JSON_VALUE(payload, '$.free_quantity') AS free_quantity,
    JSON_VALUE(payload, '$.channel') AS offer_channel,
    JSON_VALUE(payload, '$.resource_version') AS offer_resource_version,
    JSON_VALUE(payload, '$.updated_at') AS offer_updated_at,
    JSON_VALUE(payload, '$.created_at') AS offer_created_at,
    JSON_VALUE(payload, '$.is_taxable') AS is_taxable,
    JSON_VALUE(payload, '$.item_type') AS item_type,
    JSON_VALUE(payload, '$.show_description_in_invoices') AS show_description_in_invoices,
    JSON_VALUE(payload, '$.show_description_in_quotes') AS show_description_in_quotes,
    JSON_VALUE(payload, '$.deleted') AS offer_deleted,
    JSON_VALUE(payload, '$.object') AS offer_object,
    JSON_VALUE(payload, '$.trial_period') AS trial_period,
    JSON_VALUE(payload, '$.trial_period_unit') AS trial_period_unit
  FROM `variant-finance-data-project.chargebee_raw.item_prices_raw`
),
itm AS (
  SELECT
    id AS _itm_id,
    JSON_VALUE(payload, '$.item_family_id') AS _link_item_family_id,
    JSON_VALUE(payload, '$.id') AS product_id,
    JSON_VALUE(payload, '$.name') AS product_name,
    JSON_VALUE(payload, '$.external_name') AS product_external_name,
    JSON_VALUE(payload, '$.status') AS product_status,
    JSON_VALUE(payload, '$.resource_version') AS product_resource_version,
    JSON_VALUE(payload, '$.updated_at') AS product_updated_at,
    JSON_VALUE(payload, '$.item_family_id') AS product_item_family_id,
    JSON_VALUE(payload, '$.type') AS product_type,
    JSON_VALUE(payload, '$.is_shippable') AS is_shippable,
    JSON_VALUE(payload, '$.is_giftable') AS is_giftable,
    JSON_VALUE(payload, '$.enabled_for_checkout') AS enabled_for_checkout,
    JSON_VALUE(payload, '$.enabled_in_portal') AS enabled_in_portal,
    JSON_VALUE(payload, '$.metered') AS metered,
    JSON_VALUE(payload, '$.channel') AS product_channel,
    JSON_VALUE(payload, '$.deleted') AS product_deleted,
    JSON_VALUE(payload, '$.object') AS product_object,
    JSON_VALUE(payload, '$.item_applicability') AS item_applicability,
    ARRAY_LENGTH(JSON_QUERY_ARRAY(payload, '$.bundle_items')) AS bundle_items_count,
    JSON_VALUE(payload, '$.bundle_items[0].item_id') AS bundle_1_item_id,
    JSON_VALUE(payload, '$.bundle_items[0].item_type') AS bundle_1_item_type,
    JSON_VALUE(payload, '$.bundle_items[0].quantity') AS bundle_1_quantity,
    JSON_VALUE(payload, '$.bundle_items[0].price_percentage') AS bundle_1_price_percentage,
    JSON_VALUE(payload, '$.bundle_items[1].item_id') AS bundle_2_item_id,
    JSON_VALUE(payload, '$.bundle_items[1].item_type') AS bundle_2_item_type,
    JSON_VALUE(payload, '$.bundle_items[1].quantity') AS bundle_2_quantity,
    JSON_VALUE(payload, '$.bundle_items[1].price_percentage') AS bundle_2_price_percentage
  FROM `variant-finance-data-project.chargebee_raw.items_raw`
),
fam AS (
  SELECT
    id AS _fam_id,
    JSON_VALUE(payload, '$.id') AS family_id,
    JSON_VALUE(payload, '$.name') AS family_name,
    JSON_VALUE(payload, '$.status') AS family_status,
    JSON_VALUE(payload, '$.resource_version') AS family_resource_version,
    JSON_VALUE(payload, '$.updated_at') AS family_updated_at,
    JSON_VALUE(payload, '$.deleted') AS family_deleted,
    JSON_VALUE(payload, '$.object') AS family_object
  FROM `variant-finance-data-project.chargebee_raw.item_families_raw`
)

SELECT

    i.invoice_id,
    i.invoice_customer_id,
    i.invoice_subscription_id,
    i.recurring,
    i.invoice_status,
    i.invoice_date,
    i.due_date,
    i.invoice_net_term_days,
    i.invoice_price_type,
    i.invoice_exchange_rate,
    i.invoice_total,
    i.amount_due,
    i.amount_adjusted,
    i.amount_paid,
    i.paid_at,
    i.write_off_amount,
    i.credits_applied,
    i.invoice_updated_at,
    i.invoice_resource_version,
    i.invoice_deleted,
    i.invoice_object,
    i.first_invoice,
    i.amount_to_collect,
    i.invoice_round_off_amount,
    i.new_sales_amount,
    i.has_advance_charges,
    i.invoice_currency_code,
    i.invoice_base_currency_code,
    i.invoice_generated_at,
    i.is_gifted,
    i.term_finalized,
    i.invoice_channel,
    i.tax,
    i.invoice_sub_total,
    i.billing_city,
    i.billing_state_code,
    i.billing_state,
    i.billing_country,
    i.billing_zip,
    i.billing_validation_status,
    i.billing_addr_object,
    i.site_timezone,
    i.site_org_name,
    i.site_org_email,
    i.site_org_line1,
    i.site_org_city,
    i.site_org_state_code,
    i.site_org_state,
    i.site_org_country,
    i.site_org_zip,
    i.site_org_phone,
    i.site_org_website,
    i.site_org_currency,
    i.tax_origin_country,
    i.billing_first_name,
    i.billing_last_name,
    i.dunning_status,
    i.line_items_count,
    i.line1_id,
    i.line1_description,
    i.line1_entity_id,
    i.line1_entity_type,
    i.line1_amount,
    i.line1_unit_amount,
    i.line1_quantity,
    i.line1_tax_amount,
    i.line1_is_taxed,
    i.line1_tax_exempt_reason,
    i.line1_pricing_model,
    i.line1_discount_amount,
    i.line1_item_level_discount_amount,
    i.line1_date_from,
    i.line1_date_to,
    i.line1_tax_rate,
    i.line1_is_advance_charge,
    i.line1_reference_line_item_id,
    i.line2_id,
    i.line2_description,
    i.line2_entity_id,
    i.line2_entity_type,
    i.line2_amount,
    i.line2_unit_amount,
    i.line2_quantity,
    i.line2_tax_amount,
    i.line2_is_taxed,
    i.line2_tax_exempt_reason,
    i.line2_pricing_model,
    i.line2_discount_amount,
    i.line2_item_level_discount_amount,
    i.line2_date_from,
    i.line2_date_to,
    i.line2_tax_rate,
    i.line2_is_advance_charge,
    i.line2_reference_line_item_id,
    i.line3_id,
    i.line3_description,
    i.line3_entity_id,
    i.line3_entity_type,
    i.line3_amount,
    i.line3_unit_amount,
    i.line3_quantity,
    i.line3_tax_amount,
    i.line3_is_taxed,
    i.line3_tax_exempt_reason,
    i.line3_pricing_model,
    i.line3_discount_amount,
    i.line3_item_level_discount_amount,
    i.line3_date_from,
    i.line3_date_to,
    i.line3_tax_rate,
    i.line3_is_advance_charge,
    i.line3_reference_line_item_id,
    i.linked_payments_count,
    i.payment_1_txn_id,
    i.payment_1_applied_amount,
    i.payment_1_applied_at,
    i.payment_1_txn_status,
    i.payment_1_txn_date,
    i.payment_1_txn_amount,
    i.payment_2_txn_id,
    i.payment_2_applied_amount,
    i.payment_2_applied_at,
    i.payment_2_txn_status,
    i.payment_2_txn_date,
    i.payment_2_txn_amount,
    i.dunning_attempts_count,
    i.dunning_attempt_1_created_at,
    i.dunning_attempt_1_attempt,
    i.dunning_attempt_1_dunning_type,
    i.dunning_attempt_1_retry_engine,
    i.dunning_attempt_1_transaction_id,
    i.dunning_attempt_1_txn_status,
    i.dunning_attempt_1_txn_amount,
    i.dunning_attempt_2_created_at,
    i.dunning_attempt_2_attempt,
    i.dunning_attempt_2_dunning_type,
    i.dunning_attempt_2_retry_engine,
    i.dunning_attempt_2_transaction_id,
    i.dunning_attempt_2_txn_status,
    i.dunning_attempt_2_txn_amount,
    i.dunning_attempt_3_created_at,
    i.dunning_attempt_3_attempt,
    i.dunning_attempt_3_dunning_type,
    i.dunning_attempt_3_retry_engine,
    i.dunning_attempt_3_transaction_id,
    i.dunning_attempt_3_txn_status,
    i.dunning_attempt_3_txn_amount,
    i.issued_credit_notes_count,
    i.refund_cn_1_cn_id,
    i.refund_cn_1_cn_reason_code,
    i.refund_cn_1_cn_create_reason_code,
    i.refund_cn_1_cn_date,
    i.refund_cn_1_cn_total,
    i.refund_cn_1_cn_status,
    i.refund_cn_2_cn_id,
    i.refund_cn_2_cn_reason_code,
    i.refund_cn_2_cn_create_reason_code,
    i.refund_cn_2_cn_date,
    i.refund_cn_2_cn_total,
    i.refund_cn_2_cn_status,
    i.reference_transactions_count,
    i.ref_txn_1_txn_id,
    i.ref_txn_1_txn_type,
    i.ref_txn_1_txn_status,
    i.ref_txn_1_txn_date,
    i.ref_txn_1_txn_amount,
    i.ref_txn_1_applied_amount,
    i.ref_txn_1_applied_at,
    i.ref_txn_2_txn_id,
    i.ref_txn_2_txn_type,
    i.ref_txn_2_txn_status,
    i.ref_txn_2_txn_date,
    i.ref_txn_2_txn_amount,
    i.ref_txn_2_applied_amount,
    i.ref_txn_2_applied_at,
    i.applied_credits_count,
    i.applied_credit_1_cn_id,
    i.applied_credit_1_applied_amount,
    i.applied_credit_1_applied_at,
    i.applied_credit_1_cn_reason_code,
    i.applied_credit_1_cn_create_reason_code,
    i.applied_credit_1_cn_date,
    i.applied_credit_1_cn_status,
    i.applied_credit_2_cn_id,
    i.applied_credit_2_applied_amount,
    i.applied_credit_2_applied_at,
    i.applied_credit_2_cn_reason_code,
    i.applied_credit_2_cn_create_reason_code,
    i.applied_credit_2_cn_date,
    i.applied_credit_2_cn_status,
    i.adjustment_credit_notes_count,
    i.adj_cn_1_cn_id,
    i.adj_cn_1_cn_reason_code,
    i.adj_cn_1_cn_create_reason_code,
    i.adj_cn_1_cn_date,
    i.adj_cn_1_cn_total,
    i.adj_cn_1_cn_status,
    i.adj_cn_2_cn_id,
    i.adj_cn_2_cn_reason_code,
    i.adj_cn_2_cn_create_reason_code,
    i.adj_cn_2_cn_date,
    i.adj_cn_2_cn_total,
    i.adj_cn_2_cn_status,
    i.linked_orders_count,
    i.order_1_id,
    i.order_1_document_number,
    i.order_1_status,
    i.order_1_order_type,
    i.order_1_reference_id,
    i.order_1_fulfillment_status,
    i.order_1_batch_id,
    i.order_1_created_at,
    i.order_2_id,
    i.order_2_document_number,
    i.order_2_status,
    i.order_2_order_type,
    i.order_2_reference_id,
    i.order_2_fulfillment_status,
    i.order_2_batch_id,
    i.order_2_created_at,
    i.discounts_count,
    i.discount_1_amount,
    i.discount_1_description,
    i.discount_1_entity_type,
    i.discount_1_entity_id,
    i.discount_1_coupon_set_code,
    i.discount_1_discount_type,
    i.discount_2_amount,
    i.discount_2_description,
    i.discount_2_entity_type,
    i.discount_2_entity_id,
    i.discount_2_coupon_set_code,
    i.discount_2_discount_type,
    i.taxes_count,
    i.tax_1_name,
    i.tax_1_amount,
    i.tax_1_description,
    i.tax_2_name,
    i.tax_2_amount,
    i.tax_2_description,
    i.line_item_taxes_count,
    i.line_tax_1_line_item_id,
    i.line_tax_1_tax_name,
    i.line_tax_1_tax_rate,
    i.line_tax_1_is_partial_tax_applied,
    i.line_tax_1_is_non_compliance_tax,
    i.line_tax_1_taxable_amount,
    i.line_tax_1_tax_amount,
    i.line_tax_1_tax_juris_type,
    i.line_tax_1_tax_juris_name,
    i.line_tax_1_tax_juris_code,
    i.line_tax_2_line_item_id,
    i.line_tax_2_tax_name,
    i.line_tax_2_tax_rate,
    i.line_tax_2_is_partial_tax_applied,
    i.line_tax_2_is_non_compliance_tax,
    i.line_tax_2_taxable_amount,
    i.line_tax_2_tax_amount,
    i.line_tax_2_tax_juris_type,
    i.line_tax_2_tax_juris_name,
    i.line_tax_2_tax_juris_code,
    i.line_item_discounts_count,
    i.line_discount_1_line_item_id,
    i.line_discount_1_discount_type,
    i.line_discount_1_coupon_id,
    i.line_discount_1_entity_id,
    i.line_discount_1_discount_amount,
    i.line_discount_2_line_item_id,
    i.line_discount_2_discount_type,
    i.line_discount_2_coupon_id,
    i.line_discount_2_entity_id,
    i.line_discount_2_discount_amount,
    c.customer_id,
    c.customer_email,
    c.customer_auto_collection,
    c.customer_net_term_days,
    c.allow_direct_debit,
    c.customer_created_at,
    c.taxability,
    c.customer_updated_at,
    c.pii_cleared,
    c.customer_channel,
    c.customer_resource_version,
    c.customer_deleted,
    c.customer_object,
    c.cust_city,
    c.cust_state_code,
    c.cust_state,
    c.cust_country,
    c.cust_zip,
    c.cust_addr_validation_status,
    c.cust_addr_object,
    c.card_status,
    c.promotional_credits,
    c.refundable_credits,
    c.excess_payments,
    c.unbilled_charges,
    c.preferred_currency_code,
    c.customer_mrr,
    c.primary_payment_source_id,
    c.payment_method_object,
    c.payment_method_type,
    c.payment_method_reference_id,
    c.payment_method_gateway,
    c.payment_method_gateway_account_id,
    c.payment_method_status,
    c.customer_first_name,
    c.customer_last_name,
    c.cust_first_name,
    c.cust_last_name,
    c.customer_cf_afid,
    c.customer_cf_sid,
    c.customer_cf_c1,
    c.customer_cf_c2,
    c.customer_cf_c3,
    c.customer_cf_click_id,
    c.customer_cf_campaign_id,
    c.customer_cf_source,
    c.customer_cf_sub_affiliate,
    c.customer_cf_affiliate,
    c.customer_cf_aid,
    c.customer_cf_opt,
    s.subscription_id,
    s.billing_period,
    s.billing_period_unit,
    s.trial_end,
    s.subscription_auto_collection,
    s.subscription_customer_id,
    s.subscription_status,
    s.trial_start,
    s.next_billing_at,
    s.subscription_created_at,
    s.started_at,
    s.subscription_updated_at,
    s.has_scheduled_changes,
    s.subscription_channel,
    s.subscription_resource_version,
    s.subscription_deleted,
    s.subscription_object,
    s.subscription_currency_code,
    s.due_invoices_count,
    s.has_scheduled_advance_invoices,
    s.decommissioned,
    s.meta_data_funnel,
    s.meta_data_plan_id,
    s.meta_data_category,
    s.remaining_billing_cycles,
    s.cancelled_at,
    s.cancel_schedule_created_at,
    s.current_term_start,
    s.current_term_end,
    s.activated_at,
    s.subscription_mrr,
    s.subscription_exchange_rate,
    s.subscription_base_currency_code,
    s.due_since,
    s.total_dues,
    s.meta_data_afid,
    s.meta_data_sid,
    s.meta_data_c1,
    s.meta_data_c2,
    s.meta_data_c3,
    s.meta_data_click_id,
    s.meta_data_campaign_id,
    s.meta_data_source,
    s.meta_data_sub_affiliate,
    s.meta_data_affiliate,
    s.meta_data_aid,
    s.meta_data_opt,
    s.cf_afid,
    s.cf_sid,
    s.cf_c1,
    s.cf_c2,
    s.cf_c3,
    s.cf_click_id,
    s.cf_campaign_id,
    s.cf_source,
    s.cf_sub_affiliate,
    s.cf_affiliate,
    s.cf_aid,
    s.cf_opt,
    s.afid,
    s.sid,
    s.c1,
    s.c2,
    s.c3,
    s.click_id,
    s.campaign_id,
    s.source,
    s.sub_affiliate,
    s.affiliate,
    s.aid,
    s.opt,
    s.subscription_items_count,
    s.plan_item_price_id,
    s.plan_item_type,
    s.plan_quantity,
    s.plan_unit_price,
    s.plan_amount,
    s.plan_free_quantity,
    s.plan_trial_end,
    s.plan_charge_on_event,
    s.plan_charge_once,
    s.plan_billing_cycles,
    s.plan_service_period_days,
    s.plan_charge_on_option,
    s.trial_charge_item_price_id,
    s.trial_charge_item_type,
    s.trial_charge_quantity,
    s.trial_charge_unit_price,
    s.trial_charge_amount,
    s.trial_charge_free_quantity,
    s.trial_charge_trial_end,
    s.trial_charge_charge_on_event,
    s.trial_charge_charge_once,
    s.trial_charge_billing_cycles,
    s.trial_charge_service_period_days,
    s.trial_charge_charge_on_option,
    s.addon_1_item_price_id,
    s.addon_1_item_type,
    s.addon_1_quantity,
    s.addon_1_unit_price,
    s.addon_1_amount,
    s.addon_1_free_quantity,
    s.addon_1_trial_end,
    s.addon_1_charge_on_event,
    s.addon_1_charge_once,
    s.addon_1_billing_cycles,
    s.addon_1_service_period_days,
    s.addon_1_charge_on_option,
    s.addon_2_item_price_id,
    s.addon_2_item_type,
    s.addon_2_quantity,
    s.addon_2_unit_price,
    s.addon_2_amount,
    s.addon_2_free_quantity,
    s.addon_2_trial_end,
    s.addon_2_charge_on_event,
    s.addon_2_charge_once,
    s.addon_2_billing_cycles,
    s.addon_2_service_period_days,
    s.addon_2_charge_on_option,
    s.charged_items_count,
    s.charged_1_item_price_id,
    s.charged_1_last_charged_at,
    s.charged_2_item_price_id,
    s.charged_2_last_charged_at,
    t.transaction_id,
    t.transaction_customer_id,
    t.transaction_subscription_id,
    t.transaction_gateway_account_id,
    t.payment_source_id,
    t.payment_method,
    t.transaction_gateway,
    t.transaction_type,
    t.transaction_date,
    t.settled_at,
    t.transaction_exchange_rate,
    t.amount,
    t.id_at_gateway,
    t.transaction_status,
    t.transaction_updated_at,
    t.transaction_resource_version,
    t.transaction_deleted,
    t.transaction_object,
    t.masked_card_number,
    t.transaction_currency_code,
    t.transaction_base_currency_code,
    t.amount_unused,
    t.initiator_type,
    t.three_d_secure,
    t.error_code,
    t.error_text,
    t.error_detail_network_error_code,
    t.error_detail_network_error_message,
    t.error_detail_processor_error_code,
    t.error_detail_processor_error_message,
    t.error_detail_error_cause_id,
    t.error_detail_processor_advice_code,
    t.error_detail_object,
    t.error_detail_request_id,
    t.error_detail_error_code,
    t.error_detail_error_message,
    t.error_detail_recommendation_code,
    t.refunded_txn_id,
    t.txn_card_iin,
    t.txn_card_last4,
    t.txn_card_funding_type,
    t.txn_card_expiry_month,
    t.txn_card_expiry_year,
    t.txn_card_billing_city,
    t.txn_card_billing_state,
    t.txn_card_billing_country,
    t.txn_card_billing_zip,
    t.txn_card_masked_number,
    t.txn_card_brand,
    t.linked_invoices_count,
    t.txn_inv_1_invoice_id,
    t.txn_inv_1_applied_amount,
    t.txn_inv_1_applied_at,
    t.txn_inv_1_invoice_date,
    t.txn_inv_1_invoice_total,
    t.txn_inv_1_invoice_status,
    t.txn_inv_2_invoice_id,
    t.txn_inv_2_applied_amount,
    t.txn_inv_2_applied_at,
    t.txn_inv_2_invoice_date,
    t.txn_inv_2_invoice_total,
    t.txn_inv_2_invoice_status,
    t.linked_credit_notes_count,
    t.txn_cn_1_cn_id,
    t.txn_cn_1_cn_reason_code,
    t.txn_cn_1_cn_create_reason_code,
    t.txn_cn_1_cn_date,
    t.txn_cn_1_cn_total,
    t.txn_cn_1_cn_status,
    t.txn_cn_1_applied_amount,
    t.txn_cn_1_applied_at,
    t.txn_cn_1_cn_reference_invoice_id,
    t.txn_cn_2_cn_id,
    t.txn_cn_2_cn_reason_code,
    t.txn_cn_2_cn_create_reason_code,
    t.txn_cn_2_cn_date,
    t.txn_cn_2_cn_total,
    t.txn_cn_2_cn_status,
    t.txn_cn_2_applied_amount,
    t.txn_cn_2_applied_at,
    t.txn_cn_2_cn_reference_invoice_id,
    t.linked_refunds_count,
    t.txn_refund_1_txn_id,
    t.txn_refund_1_txn_status,
    t.txn_refund_1_txn_date,
    t.txn_refund_1_txn_amount,
    t.txn_refund_2_txn_id,
    t.txn_refund_2_txn_status,
    t.txn_refund_2_txn_date,
    t.txn_refund_2_txn_amount,
    cn.cn_count,
    cn.cn_total_amount_refunded,
    cn.cn_total_credit_amount,
    cn.cn_id,
    cn.cn_type,
    cn.cn_reason_code,
    cn.cn_status,
    cn.cn_date,
    cn.cn_price_type,
    cn.cn_exchange_rate,
    cn.cn_total,
    cn.cn_amount_allocated,
    cn.cn_amount_refunded,
    cn.cn_amount_available,
    cn.cn_refunded_at,
    cn.cn_generated_at,
    cn.cn_updated_at,
    cn.cn_channel,
    cn.cn_resource_version,
    cn.cn_deleted,
    cn.cn_object,
    cn.cn_create_reason_code,
    cn.cn_currency_code,
    cn.cn_round_off_amount,
    cn.cn_fractional_correction,
    cn.cn_base_currency_code,
    cn.cn_sub_total,
    cn.cn_customer_notes,
    cn.cn_linked_refunds_count,
    cn.cn_refund_1_txn_id,
    cn.cn_refund_1_txn_status,
    cn.cn_refund_1_txn_date,
    cn.cn_refund_1_txn_amount,
    cn.cn_refund_1_applied_amount,
    cn.cn_refund_1_applied_at,
    cn.cn_refund_2_txn_id,
    cn.cn_refund_2_txn_status,
    cn.cn_refund_2_txn_date,
    cn.cn_refund_2_txn_amount,
    cn.cn_refund_2_applied_amount,
    cn.cn_refund_2_applied_at,
    cn.cn_notes_1,
    ps.card_id,
    ps.card_updated_at,
    ps.card_resource_version,
    ps.card_deleted,
    ps.card_object,
    ps.card_customer_id,
    ps.card_type,
    ps.reference_id,
    ps.card_status AS card_status_2,
    ps.card_gateway,
    ps.card_gateway_account_id,
    ps.issuing_country,
    ps.ip_address,
    ps.card_created_at,
    ps.card_iin,
    ps.card_last4,
    ps.card_funding_type,
    ps.card_expiry_month,
    ps.card_expiry_year,
    ps.card_billing_city,
    ps.card_billing_state_code,
    ps.card_billing_state,
    ps.card_billing_country,
    ps.card_billing_zip,
    ps.card_masked_number,
    ps.card_object_2,
    ps.card_brand,
    ps.paypal_email,
    ps.paypal_agreement_id,
    ps.paypal_object,
    ip.offer_id,
    ip.offer_name,
    ip.offer_item_family_id,
    ip.item_id,
    ip.offer_status,
    ip.offer_external_name,
    ip.pricing_model,
    ip.price,
    ip.period,
    ip.offer_currency_code,
    ip.period_unit,
    ip.free_quantity,
    ip.offer_channel,
    ip.offer_resource_version,
    ip.offer_updated_at,
    ip.offer_created_at,
    ip.is_taxable,
    ip.item_type,
    ip.show_description_in_invoices,
    ip.show_description_in_quotes,
    ip.offer_deleted,
    ip.offer_object,
    ip.trial_period,
    ip.trial_period_unit,
    itm.product_id,
    itm.product_name,
    itm.product_external_name,
    itm.product_status,
    itm.product_resource_version,
    itm.product_updated_at,
    itm.product_item_family_id,
    itm.product_type,
    itm.is_shippable,
    itm.is_giftable,
    itm.enabled_for_checkout,
    itm.enabled_in_portal,
    itm.metered,
    itm.product_channel,
    itm.product_deleted,
    itm.product_object,
    itm.item_applicability,
    itm.bundle_items_count,
    itm.bundle_1_item_id,
    itm.bundle_1_item_type,
    itm.bundle_1_quantity,
    itm.bundle_1_price_percentage,
    itm.bundle_2_item_id,
    itm.bundle_2_item_type,
    itm.bundle_2_quantity,
    itm.bundle_2_price_percentage,
    fam.family_id,
    fam.family_name,
    fam.family_status,
    fam.family_resource_version,
    fam.family_updated_at,
    fam.family_deleted,
    fam.family_object
FROM i
LEFT JOIN c   ON c._c_id     = i._link_customer_id
LEFT JOIN s   ON s._s_id     = i._link_subscription_id
LEFT JOIN t   ON t._link_invoice_id = i._i_id
LEFT JOIN cn  ON cn._link_invoice_id = i._i_id
LEFT JOIN ps  ON ps._ps_id   = c._link_payment_source_id
LEFT JOIN ip  ON ip._ip_id   = s._link_item_price_id
LEFT JOIN itm ON itm._itm_id = ip._link_item_id
LEFT JOIN fam ON fam._fam_id = itm._link_item_family_id;
